version: "3"
services:
    app:
        depends_on:
            - postgres
        build: 
          context: ./
          dockerfile: ./server/Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
    postgres:
        image: "postgres:12"
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}